from time import sleep
import random


def login():
    tries = 3
    while tries >= 0:
        print("Login, to play Rock, paper and scissors!")
        username = str(input("Please Enter your username: "))
        password = int(input("Please enter your pin in the screen: "))
        if username == ("SausageAndWaffles") and password == (71556):
            print("Correct..fetching you data in few seconds...")
            return True
        else:
            print('Incorrect username or password please try again.')
            tries = tries + 1
    print("Incorrect password and system is self-destryoing for attempts in 3 seconds...")
    sleep(3)
    return False


def start_game():

    name = str(input("Please, enter your name"))
    print(f"Hello {name}, and welcome Guess the number which is generated by computer!")
    if login():

        number = random.randint(1, 9)
        chances = 0

        print("Guess a number (between 1 and 9):")
        while chances < 1:
            guess = int(input())
            chances = chances + 1
            if guess == number:
                print(f"The number you guessed was: {guess} and it is the right number!! Congratulations! and you guessed in {chances} attempts!")
                break

            elif guess < number:
                print("Your guess was too low: Guess a number higher than", guess)

            else:
                print("Your guess was too high: Guess a number lower than", guess)


        if not chances > 1:
            print("Sorry you lost, try again next time, The number is", number)


start_game()
