import random
from time import sleep


def login():
    tries = 0
    while tries < 3:
        print("Login, to play Guess the number!")
        username = str(input("Please enter your username here: "))
        password = str(input("Please enter your password here :"))
        if username == ("SausageAndWaffles") and password == ("sdDsCF45"):
            print("Correct data..fetching your required game...")
            return True
        else:
            print("Incorrect password, please try again.")
            tries = tries + 1
    print("Incorrect password entered wrong 3 times, system self destroying...in 3 seconds")
    sleep(3)
    return False


def start_game():
        print("Hello welcome to Guess the number..in which you have to guess the number which is generated by a computer.")
        if login():

            number = random.randint(1,20)
            chances = 0

            print("Guess the number between 0 - 20")
            while chances < 100:
                guess = int(input())
                if guess == number:
                    chances = chances + 1
                    print(f"The number you've guessed was:{guess} and congratulations because you guessed the correct number in {chances}!")
                    break

                elif guess < number:
                    print("The number you provided was too low guess a higher number!")


                else:
                    print("The number you provided was too high guess a low number!")


            if not chances < 100:
                print("Sorry you lost and you have no tries left, please try again next time!")


start_game()
